pub mod audio;
pub mod linking;
pub mod logs;
pub mod pitch;
pub mod recordings;
pub mod sentences;
pub mod status;
pub mod video;
pub mod temp_recordings;
pub mod cutter;
#[path = "whisper_facade.rs"]
pub mod whisper;
